
export const districtsWithMunicipalities = [
    { district: "Taplejung", municipalities: ["Phungling", "Aathrai Tribeni", "Sidingwa", "Phaktanglung", "Mikwa Khola", "Meringden", "Maiwa Khola", "Yangwarak", "Sirijangha"] },
    { district: "Panchthar", municipalities: ["Phidim", "Miklajung", "Phalgunanda", "Hilihang", "Phalelung", "Yangwarak", "Kummayak", "Tumbewa"] },
    { district: "Ilam", municipalities: ["Ilam", "Deumai", "Mai", "Suryodaya", "Phakphokthum", "Mai Jogmai", "Chulachuli", "Rong", "Mangsebung", "Sandakpur"] },
    { district: "Jhapa", municipalities: ["Mechinagar", "Damak", "Kankai", "Bhadrapur", "Shivasatakshi", "Gauradaha", "Birtamod", "Arjundhara", "Gauriganj", "Barhadashi", "Jhapa", "Kamal", "Kachankawal", "Haldibari", "Buddha Shanti"] },
    { district: "Morang", municipalities: ["Biratnagar", "Sunawarshi", "Rangeli", "Patahrisanischare", "Letang", "Belbari", "Sundarharaincha", "Urlabari", "Dhanpalthan", "Gramthan", "Jahada", "Budhiganga", "Katahari", "Kanepokhari", "Kerabari", "Miklajung"] },
    { district: "Sunsari", municipalities: ["Inaruwa", "Dharan", "Itahari", "Ramdhuni", "Barahachhetra", "Duhabi", "Koshi", "Harinagar", "Dewanganj", "Gadhi", "Barju", "Bhokraha"] },
    { district: "Dhankuta", municipalities: ["Dhankuta", "Pakhribas", "Mahalaxmi", "Sangurigadhi", "Chhathar Jorpati", "Shahidbhumi", "Chaubise"] },
    { district: "Terhathum", municipalities: ["Myanglung", "Laligurans", "Aathrai", "Phedap", "Chhathar", "Menchayayem"] },
    { district: "Sankhuwasabha", municipalities: ["Khandbari", "Chainpur", "Dharmadevi", "Panchkhapan", "Madi", "Bhotkhola", "Chichila", "Makalu", "Sabhapokhari", "Silichong"] },
    { district: "Bhojpur", municipalities: ["Bhojpur", "Shadanand", "Arun", "Aamchowk", "Hatuwagadhi", "Pauwadungma", "Ramprasad Rai", "Salpasilichho", "Tyamke Maiyum"] },
    { district: "Okhaldhunga", municipalities: ["Siddhicharan", "Champadevi", "Chisankhugadhi", "Khijidemba", "Likhu", "Manebhanjyang", "Molung", "Sunkoshi"] },
    { district: "Khotang", municipalities: ["Diktel Rupakot Majhuwagadhi", "Halesi Tuwachung", "Aiselukharka", "Barahapokhari", "Diprung", "Jantedhunga", "Kepilasgadhi", "Khotehang", "Lamidanda", "Sakela"] },
    { district: "Solukhumbu", municipalities: ["Solududhkunda", "Dudhakaushika", "Necha Salyan", "Dudhkoshi", "Mahakulung", "Likhupike", "Khumbu Pasang Lhamu", "Sotang"] },
    { district: "Udayapur", municipalities: ["Katari", "Chaudandigadhi", "Triyuga", "Belaka", "Rautamai", "Udayapurgadhi", "Tapli", "Limchungbung"] },
    { district: "Saptari", municipalities: ["Rajbiraj", "Khadak", "Bodebarsain", "Dakneshwari", "Hanumannagar Kankalini", "Saptakoshi", "Kanchanrup", "Shambhunath", "Surunga", "Agnisaira Krishnasavaran", "Balan-Bihul", "Bishnupur", "Chhinnamasta", "Mahadeva", "Rupani", "Tilathi Koiladi", "Tirahut"] },
    { district: "Siraha", municipalities: ["Siraha", "Dhangadhimai", "Lahan", "Golbazar", "Mirchaiya", "Kalyanpur", "Sukhipur", "Karjanha", "Arnama", "Aurahi", "Bariyarpatti", "Bhagwanpur", "Bishnupur", "Laxmipur Patari", "Naraha", "Nawarajpur", "Sakhuwanankarkatti"] },
    { district: "Dhanusha", municipalities: ["Janakpurdham", "Chhireshwarnath", "Ganeshman Charnath", "Dhanushadham", "Nagarain", "Bideha", "Mithila", "Sabaila", "Kamala", "Aurahi", "Bateshwar", "Dhanauji", "Hansapur", "Janaknandani", "Lakshminiya", "Mithila Bihari", "Mukhiyapatti Musaharmiya"] },
    { district: "Mahottari", municipalities: ["Jaleshwar", "Bardibas", "Gaushala", "Loharpatti", "Manara Shiswa", "Matihani", "Bhangaha", "Ramgopalpur", "Aurahi", "Balawa", "Ekdara", "Mahottari", "Pipra", "Sonama", "Samsi"] },
    { district: "Sarlahi", municipalities: ["Malangwa", "Haripur", "Haripurwa", "Hariwan", "Ishwarpur", "Lalbandi", "Bagmati", "Barahathwa", "Balara", "Godaita", "Kabilasi", "Bramhapuri", "Chakraghatta", "Chandranagar", "Dhankaul", "Kaudena", "Parsa", "Ramnagar", "Bishnu"] },
    { district: "Sindhuli", municipalities: ["Dudhauli", "Kamalamai", "Phikkal", "Golanjor", "Ghyanglekh", "Hariharpurgadhi", "Marin", "Sunkoshi", "Tinpatan"] },
    { district: "Ramechhap", municipalities: ["Manthali", "Ramechhap", "Doramba", "Gokulganga", "Khandadevi", "Likhu", "Sunapati", "Umakunda"] },
    { district: "Dolakha", municipalities: ["Bhimeshwar", "Jiri", "Bigu", "Gaurishankar", "Kalinchok", "Melung", "Sailung", "Tamakoshi", "Baiteshwor"] },
    { district: "Sindhupalchok", municipalities: ["Chautara Sangachokgadhi", "Barhabise", "Melamchi", "Balephi", "Bhotekoshi", "Helambu", "Indrawati", "Jugal", "Panchpokhari Thangpal", "Sunkoshi", "Tripurasundari", "Lisankhu Pakhar"] },
    { district: "Kavrepalanchok", municipalities: ["Dhulikhel", "Banepa", "Panauti", "Panchkhal", "Namobuddha", "Mandandeupur", "Bethanchok", "Bhumlu", "Chaurideurali", "Khanikhola", "Mahabharat", "Roshi", "Temal"] },
    { district: "Lalitpur", municipalities: ["Lalitpur", "Godawari", "Mahalaxmi", "Bagmati", "Konjyosom", "Mahankal"] },
    { district: "Bhaktapur", municipalities: ["Bhaktapur", "Changunarayan", "Madhyapur Thimi", "Suryabinayak"] },
    { district: "Kathmandu", municipalities: ["Kathmandu", "Budhanilkantha", "Chandragiri", "Dakshinkali", "Gokarneshwar", "Kageshwari-Manohara", "Kirtipur", "Nagarjun", "Shankharapur", "Tarakeshwar", "Tokha"] },
    { district: "Nuwakot", municipalities: ["Bidur", "Belkotgadhi", "Dupcheshwar", "Kakani", "Kispang", "Likhu", "Meghang", "Panchakanya", "Shivapuri", "Suryagadhi", "Tadi", "Tarkeshwar"] },
    { district: "Rasuwa", municipalities: ["Gosaikunda", "Aamachhodingmo", "Kalika", "Naukunda", "Parbatikunda"] },
    { district: "Dhading", municipalities: ["Dhadingbesi", "Nilkantha", "Dhunibesi", "Galchhi", "Gajuri", "Gangajamuna", "Jwalamukhi", "Thakre", "Benighat Rorang", "Ruby Valley", "Siddhalek", "Netrawati Dabjong", "Khaniyabas"] },
    { district: "Makwanpur", municipalities: ["Hetauda", "Thaha", "Bagmati", "Bakaiya", "Bhimphedi", "Indrasarowar", "Kailash", "Makwanpurgadhi", "Manahari", "Raksirang"] },
    { district: "Rautahat", municipalities: ["Chandrapur", "Garuda", "Gaur", "Baudhimai", "Brindaban", "Dewahi Gonahi", "Gadhimai", "Gujara", "Ishanath", "Katahariya", "Madhav Narayan", "Maulapur", "Paroha", "Phatuwa Bijayapur", "Rajdevi", "Rajpur", "Durga Bhagwati", "Yamunamai"] },
    { district: "Bara", municipalities: ["Kalaiya", "Jitpur-Simara", "Kolhabi", "Nijgadh", "Mahagadhimai", "Simraungadh", "Pacharauta", "Adarsh Kotwal", "Baragadhi", "Bishrampur", "Devtal", "Karaiyamai", "Parwanipur", "Prasauni", "Pheta", "Suwarna"] },
    { district: "Parsa", municipalities: ["Birgunj", "Bahudarmai", "Parsagadhi", "Bindabasini", "Chhipaharmai", "Dhobini", "Jagarnathpur", "Jirabhawani", "Kalikamai", "Pakaha Mainpur", "Paterwa Sugauli", "Pokhariya", "Sakhuwa Prasauni", "Thori"] },
    { district: "Chitwan", municipalities: ["Bharatpur", "Kalika", "Khairhani", "Madi", "Rapti", "Ratnanagar", "Ichchhakamana"] },
    { district: "Gorkha", municipalities: ["Gorkha", "Palungtar", "Aarughat", "Ajirkot", "Barpak Sulikot", "Bhimsen Thapa", "Chum Nubri", "Dharche", "Gandaki", "Sahid Lakhan", "Siranchok"] },
    { district: "Manang", municipalities: ["Chame", "Narpa Bhumi", "Nason", "Manang Disyang"] },
    { district: "Lamjung", municipalities: ["Besishahar", "Madhyanepal", "Rainas", "Sundarbazar", "Dordi", "Dudhpokhari", "Kwholasothar", "Marsyangdi"] },
    { district: "Tanahun", municipalities: ["Bhanu", "Bhimad", "Byas", "Shuklagandaki", "Anbukhaireni", "Bandipur", "Devghat", "Ghiring", "Myagde", "Rishing"] },
    { district: "Kaski", municipalities: ["Pokhara", "Annapurna", "Machhapuchchhre", "Madi", "Rupa"] },
    { district: "Syangja", municipalities: ["Putalibazar", "Galyang", "Chapakot", "Waling", "Aandhikhola", "Arjunchaupari", "Biruwa", "Harinas", "Kaligandaki", "Phedikhola", "Bhirkot"] },
    { district: "Mustang", municipalities: ["Gharapjhong", "Thasang", "Lomanthang", "Lo-Ghekar Damodarkunda", "Baragung Muktichhetra"] },
    { district: "Parbat", municipalities: ["Kushma", "Phalewas", "Bihadi", "Jaljala", "Mahashila", "Modi", "Paiyun"] },
    { district: "Myagdi", municipalities: ["Beni", "Annapurna", "Dhaulagiri", "Malika", "Mangala", "Raghuganga"] },
    { district: "Nawalpur", municipalities: ["Kawasoti", "Gaidakot", "Devchuli", "Madhyabindu", "Bulingtar", "Bungdikali", "Hupsekot", "Binayi Tribeni"] },
    { district: "Parasi", municipalities: ["Ramgram", "Sunwal", "Bardaghat", "Pratappur", "Sarawal", "Susta", "Palhinandan"] },
    { district: "Rupandehi", municipalities: ["Butwal", "Devdaha", "Lumbini Sanskritik", "Sainamaina", "Siddharthanagar", "Tilottama", "Gaidahawa", "Kanchan", "Kotahimai", "Marchawari", "Mayadevi", "Omsatiya", "Rohini", "Sammarimai", "Siyari", "Suddhodhan"] },
    { district: "Kapilvastu", municipalities: ["Kapilvastu", "Banganga", "Buddhabhumi", "Shivaraj", "Krishnanagar", "Maharajganj", "Mayadevi", "Yashodhara", "Suddhodhan", "Bijaynagar"] },
    { district: "Palpa", municipalities: ["Tansen", "Rampur", "Bagnaskali", "Mathagadhi", "Nisdi", "Purbakhola", "Rainadevi Chhahara", "Rambha", "Ribdikot", "Tinau"] },
    { district: "Arghakhanchi", municipalities: ["Sandhikharka", "Sitganga", "Bhumekasthan", "Chhatradev", "Malarani", "Panini"] },
    { district: "Gulmi", municipalities: ["Resunga", "Musikot", "Chandrakot", "Chhatrakot", "Darbar Devisthan", "Dhurkot", "Gulmi Durbar", "Isma", "Kaligandaki", "Madane", "Malika", "Ruru"] },
    { district: "Pyuthan", municipalities: ["Pyuthan", "Sworgadwari", "Gaumukhi", "Jhimruk", "Mallarani", "Mandavi", "Nauwahini", "Sarumarani", "Airawati"] },
    { district: "Rolpa", municipalities: ["Rolpa", "Thabang", "Sunilsmriti", "Lungri", "Sunchhahari", "Madi", "Runtigadhi", "Triveni", "Pariwartan", "Gangadev"] },
    { district: "Rukum East", municipalities: ["Putha Uttarganga", "Bhume", "Sisne"] },
    { district: "Rukum West", municipalities: ["Musikot", "Aathbiskot", "Chaurjahari", "Banphikot", "Sani Bheri", "Triveni"] },
    { district: "Salyan", municipalities: ["Shaarda", "Bangad Kupinde", "Bagchaur", "Darma", "Kapurkot", "Kalimati", "Chhatreshwari", "Siddha Kumakh", "Tribeni", "Kumakh"] },
    { district: "Jajarkot", municipalities: ["Bheri", "Chhedagad", "Nalgad", "Barekot", "Kushe", "Junichande", "Shivalaya"] },
    { district: "Dolpa", municipalities: ["Thuli Bheri", "Tripurasundari", "Dolpo Buddha", "She Phoksundo", "Jagadulla", "Mudkechula", "Kaike", "Chharka Tangsong"] },
    { district: "Humla", municipalities: ["Simkot", "Adanchuli", "Chankheli", "Kharpunath", "Namkha", "Sarkegad", "Tanjakot"] },
    { district: "Jumla", municipalities: ["Chandannath", "Kankasundari", "Sinja", "Hima", "Tila", "Guthichaur", "Tatopani", "Patrasi"] },
    { district: "Mugu", municipalities: ["Chhayanath Rara", "Mugum Karmarong", "Soru", "Khatyad"] },
    { district: "Kalikot", municipalities: ["Khandachakra", "Raskot", "Triveni", "Pachaljharana", "Palata", "Naraharinath", "Sanni Triveni", "Mahawai", "Shubha Kalika"] },
    { district: "Dailekh", municipalities: ["Narayan", "Dullu", "Aathabis", "Chamunda Bindrasaini", "Bhagawatimai", "Bhairabi", "Dungeshwar", "Gurans", "Mahabu", "Naumule", "Thantikandh"] },
    { district: "Surkhet", municipalities: ["Birendranagar", "Bheriganga", "Gurbhakot", "Panchapuri", "Lekbesi", "Chaukune", "Barahatal", "Chingad", "Simta"] },
    { district: "Banke", municipalities: ["Nepalgunj", "Kohalpur", "Rapti-Sonari", "Narainapur", "Duduwa", "Janaki", "Khajura", "Baijanath"] },
    { district: "Bardiya", municipalities: ["Gulariya", "Madhuwan", "Rajapur", "Thakurbaba", "Bansgadhi", "Barbardiya", "Badhaiyatal", "Geruwa"] },
    { district: "Dang", municipalities: ["Ghorahi", "Tulsipur", "Lamahi", "Banglachuli", "Dangisharan", "Gadhawa", "Rapti", "Shantinagar", "Babai", "Rajpur"] },
    { district: "Kailali", municipalities: ["Dhangadhi", "Tikapur", "Ghodaghodi", "Lamki Chuha", "Bhajani", "Godawari", "Gauriganga", "Janaki", "Bardagoriya", "Joshipur", "Kailari", "Mohanyal", "Chure"] },
    { district: "Doti", municipalities: ["Dipayal Silgadhi", "Shikhar", "Adarsha", "Badikedar", "Bogatan-Phudsil", "Jorayal", "K.I.Singh", "Purbichauki", "Sayal"] },
    { district: "Bajhang", municipalities: ["Jaya Prithvi", "Bungal", "Bitthadchir", "Chhabis Pathivera", "Durgathali", "Kedarasyu", "Khaptadchhanna", "Masta", "Saipal", "Surma", "Talkot", "Thalara"] },
    { district: "Bajura", municipalities: ["Badimalika", "Triveni", "Budhiganga", "Budhinanda", "Gaumul", "Himali", "Jagannath", "Khaptad Chhededaha", "Swami Kartik Khapar"] },
    { district: "Kanchanpur", municipalities: ["Bhimdatta", "Punarbas", "Bedkot", "Mahakali", "Shuklaphanta", "Belauri", "Krishnapur", "Beldandi", "Laljhadi"] },
    { district: "Dadeldhura", municipalities: ["Amargadhi", "Parshuram", "Aalital", "Bhageshwar", "Ganyapdhura", "Navadurga", "Ajaymeru"] },
    { district: "Baitadi", municipalities: ["Dasharathchand", "Patan", "Melauli", "Purchaudi", "Dilasaini", "Dogdakedar", "Pancheshwar", "Shivanath", "Sigas", "Sunarya"] },
    { district: "Darchula", municipalities: ["Mahakali", "Shailyashikhar", "Apihimal", "Byas", "Duhun", "Lekam", "Malikarjun", "Marma", "Naugad"] }
];

    