'use client';

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { Button } from './button';
import { ScrollArea } from './scroll-area';

interface TermsDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function TermsDialog({ open, onOpenChange }: TermsDialogProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle className="text-center text-2xl">Terms of Service</DialogTitle>
          <DialogDescription className="text-center text-muted-foreground pt-2">
            Last Updated: December 15, 2025
          </DialogDescription>
        </DialogHeader>
        <ScrollArea className="h-[60vh] p-6 border rounded-md bg-background/50">
          <div className="prose prose-sm dark:prose-invert max-w-none text-muted-foreground space-y-4">
            <h3 className="font-semibold text-foreground">1. Acceptance of Terms</h3>
            <p>
              By accessing and using OmniTools AI ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to all of these Terms, do not use this Service.
            </p>
            <h3 className="font-semibold text-foreground">2. Description of Service</h3>
            <p>
              OmniTools AI provides a collection of free online tools, including but not limited to a Europass CV Builder, an AI Photo Enhancer for upscaling images to 8K, and video creation tools. All tools are provided "as-is" and are intended for personal and professional use.
            </p>
            <h3 className="font-semibold text-foreground">3. User Conduct and Responsibilities</h3>
            <ul>
                <li>You are solely responsible for the content (e.g., text, images, videos) that you upload, process, and download through our Service.</li>
                <li>You agree not to use the Service to create any content that is unlawful, harmful, defamatory, or infringing on intellectual property rights.</li>
                <li>The dummy flight tickets, hotel bookings, and travel itineraries generated by the Visa Toolkit are for visa application purposes only and hold no real-world value. They cannot be used for actual travel.</li>
            </ul>
            <h3 className="font-semibold text-foreground">4. Data Privacy and Content Ownership</h3>
            <p>
                We prioritize your privacy. Please review our Privacy Policy for details on data handling.
            </p>
            <ul>
                <li><strong>Automatic Deletion:</strong> All files you upload are automatically deleted from our servers within 24 hours. We do not store your personal content.</li>
                <li><strong>Ownership:</strong> You retain full ownership of all content you create and process through our tools. We claim no rights to your CVs, photos, or videos.</li>
            </ul>
            <h3 className="font-semibold text-foreground">5. Disclaimer of Warranties</h3>
            <p>
              The Service is provided on an "as-is" and "as-available" basis. OmniTools AI makes no warranty that the service will be uninterrupted, timely, secure, or error-free. The use of any tool is at your own discretion and risk.
            </p>
            <h3 className="font-semibold text-foreground">6. Limitation of Liability</h3>
            <p>
                In no event shall OmniTools AI or its owner be liable for any direct, indirect, incidental, or consequential damages arising out of the use or inability to use the Service.
            </p>
            <h3 className="font-semibold text-foreground">7. Changes to Terms</h3>
            <p>
                We reserve the right to modify these Terms at any time. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms.
            </p>
          </div>
        </ScrollArea>
        <DialogFooter>
          <Button onClick={() => onOpenChange(false)}>Close</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
